# Generated by Django 5.1.2 on 2024-11-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_chatelectronic_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatElectronic',
        ),
    ]
